# Porta (opcional)
quarkus.http.port=8081

# DataSource principal
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://db.daidvyjgslgbntpozxbe.supabase.co:5432/postgres?user=postgres&password=Senai2026ProjAplicado
quarkus.datasource.jdbc.max-size=8


# Hibernate - SEM validação para Supabase
quarkus.hibernate-orm.validate-in-dev-mode=false
quarkus.hibernate-orm.schema-management.strategy=update
# Logs
quarkus.log.level=INFO







