mp.jwt.verify.issuer=foodtruck-app

# Configuração para DEV
%dev.smallrye.jwt.sign.key.location=privateKey.pem
%dev.mp.jwt.verify.publickey.location=publicKey.pem

# Configuração para PROD
%prod.smallrye.jwt.sign.key.location=privateKey.pem
%prod.mp.jwt.verify.publickey.location=publicKey.pem