# application-prod.properties

# Usa a porta injetada pelo Render ou 8080 como fallback
quarkus.http.port=${PORT:8080}

# BANCO DE DADOS:
quarkus.datasource.jdbc.url=${DB_URL}
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}

# Substitua pela URL real do seu front-end na Vercel
quarkus.http.cors.origins=https://projeto-aplicado-ii.vercel.app/

# Hibernate em Prod
quarkus.hibernate-orm.schema-generation.database.generation=validate

# ViaCep API
quarkus.rest-client.viacep-api.url=https://viacep.com.br
quarkus.rest-client.viacep-api.connect-timeout=3000
quarkus.rest-client.viacep-api.read-timeout=3000