# Porta (opcional)
quarkus.http.port=8081

# DataSource principal
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://db.daidvyjgslgbntpozxbe.supabase.co:5432/postgres?user=postgres&password=Senai2026ProjAplicado
quarkus.datasource.jdbc.max-size=8

# CORS Configuration
quarkus.http.cors.~.enabled=true
quarkus.http.cors.~.origins=http://localhost:5173,http://localhost:3000
quarkus.http.cors.~.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.~.headers=Content-Type,Authorization

# Hibernate - SEM validação para Supabase
quarkus.hibernate-orm.validate-in-dev-mode=false
quarkus.hibernate-orm.schema-management.strategy=update
# Logs
quarkus.log.level=INFO







